# Levantamiento de datos (Explicación técnica)

Los datos fueron obtenidos de la plataforma TWEET BINDER mediante consultas como las siguientes:

``` 
"x" (y1 OR y2 OR z1 OR z2) -is:retweet since:fecha1 until:fecha2
```
Donde los terminos manejan la siguiente correspondencia según la explicacion anteior:

```
    - x : vivir sabroso
    - y1, y2 : negro, negra
    - z1, z2 : petro, francia
```

Así, se encasilla la población bajo los tres marcos

## Resultados de las consultas

Los resultados obtenidos de las consultas en TWEET BINDER son porporcionados en distintos formatos descargables, junto con un dashboard de estadisticas generales. Este dashboard ofrece conteos como : 

```  
- Total Posts  
- Economic value  
- Total impressions  
- Potential impressions  
- Potential reach  
- Total contributors  
- Posts per contributor  
- Followers per contributor  
- Original posts  
- Original contributors  
- Original posts per contributor  
- Text posts  
- Replies  
- Reposts  
- Links and images  
- Date range  
```
Incluso se ofrece la visualización especifica de los posteos mas representativos. Luego, en la descarga se encontraban disponibles los formatos:

```  
-Excel
-PDF
-CSV
-JSON
...

```
En donde se ha seleccionado el formato "Excel" para el equilibrio entre el analisis riguroso que requiere y una posible proporción de los datos. Los datos en excel ofrecen distintas hojas con informacion muy util:
1. la primera hojas "stats", útil para conocer el contenido general de la descarga, proporciona:
``` 
- Total posts  
- Original posts  
- Reposts  
- Text posts  
- Replies  
- Links & pictures  
- Impressions  
- Followers per contributor  
- Reach  
- Contributors  
- Economic value  
- Contributors value  
- Post value mean  
- Likes  
- Likes per contributor  
- Reposts per contributor  
- Quotes  
- Bookmarks  
- Average posts per contributor  
- 1 post  
- 2 posts  
- 3 posts  
```
2. La segunda "posts", central en este analisis de datos, proporciona:
```

- User  
- Username  
- UTC Date  
- Post  
- Binders  
- Permalink  
- Reposts  
- Likes count  
- Impressions  
- Quotes  
- Replies  
- Bookmarks  
- Post value  
```
3. La Tercera hoja "Contirbutors" ofrece información importante capaz de complementar en análisis:
```

- User  
- Username  
- Location  
- Age (YYYY/MM/DD)  
- Total posts  
- Reposts  
- Images  
- Links  
- Chats  
- Text posts  
- Impressions  
- Quotes  
- Replies  
- Bookmarks  
- Post value  
- Followers  
- Following  
- Bio  
- User value  
- Posts value  


```

### Muestra de 2024

In [1]:
import pandas as pd

In [6]:
df = pd.read_excel("../data/2024-01-2024-05.xlsx", sheet_name="posts")

Finalmente los datos se ven expresados así. Dónde resalta la importancia de la columna "post", que contiene la cadena de STRING con la publicación/comentario hecha por las personas, contenido que será analizado.

In [7]:
df

,User,Username,UTC Date,post,Binders,Permalink,reposts,Likes count,Impressions,Quotes,Replies,Bookmarks,post value
0,Betty,@salvemosacali,2024-05-31 22:33:34,@GiovannyEnciso @petrogustavo Si tanto les gus...,NaN,https://www.x.com/user/status/1796671387643334695,0,0,5,0,0,0,0.17
1,Carlos Santamaria,@CarlosS14767455,2024-05-31 22:24:39,@GiovannyEnciso @petrogustavo Si les gusta tan...,NaN,https://www.x.com/user/status/1796669147427840354,0,0,1,0,0,0,0.00
2,José Acevedo,@joseAcevedo69,2024-05-31 21:57:39,@JoseWilmerPache Eso es bueno ver cómo están c...,NaN,https://www.x.com/user/status/1796662349505425835,4,25,641,0,3,0,0.01
3,Tamerlan,@Tamerlan232,2024-05-31 21:13:09,@Carloss45893257 @RenataSokolov Tranquilo que ...,NaN,https://www.x.com/user/status/1796651152169214366,0,1,95,0,1,0,0.42
4,Gomez David,@GomezDa78155177,2024-05-31 21:03:38,@GiovannyEnciso @petrogustavo Los colombianos ...,NaN,https://www.x.com/user/status/1796648756240101747,1,7,48,0,0,0,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3804,JACOB HAN'S,@AlvaroDiegoGal2,2024-01-01 04:43:44,@RevistaSemana @RenataSokolov Ijue la traba de...,NaN,https://www.x.com/user/status/1741681590621622340,0,0,2,0,0,0,0.05
3805,MYRIAM ÁLVAREZ,@MYRIAMLVAREZ6,2024-01-01 04:22:11,@infopresidencia @petrogustavo @Mineducacion E...,NaN,https://www.x.com/user/status/1741676164396032331,0,0,4,0,0,0,0.01
3806,The Road Dog,@Marinillo9,2024-01-01 04:13:02,@InesBetancur1 Lo de vivir sabroso era para el...,NaN,https://www.x.com/user/status/1741673865137238372,0,0,185,0,1,0,0.01
3807,luis lopez,@luislop55692606,2024-01-01 03:18:55,@CatalinaAlfrez1 @GustavoBolivar Viven en la o...,NaN,https://www.x.com/user/status/1741660243027800226,0,0,9,0,0,0,0.00
3808,Cáustico,@puntillazofinal,2024-01-01 02:43:32,Esta si es la encuesta. Feliz año para los que...,NaN,https://www.x.com/user/status/1741651341473202364,1,2,74,0,0,0,16.54

In [12]:
df[["post"]].iloc[:30]

                                                 post
0   @GiovannyEnciso @petrogustavo Si tanto les gus...
1   @GiovannyEnciso @petrogustavo Si les gusta tan...
2   @JoseWilmerPache Eso es bueno ver cómo están c...
3   @Carloss45893257 @RenataSokolov Tranquilo que ...
4   @GiovannyEnciso @petrogustavo Los colombianos ...
5   @EnterateCali Ratasss. Por eso son seguidores ...
6   @paulabolivar Petro dijo que iban a vivir sabr...
7   @FisicoImpuro Cuando petro sea presidente el v...
8   @dicalaca18 PS que el problema no era la corru...
9   @CelsoTeteC Cuando petro sea presidente todo e...
10  @MariaA_PardoJ a vivir sabroso como francia la...
11  @GoezTeresita @IvanDuque @CeDemocratico Que ca...
12  Como olvidar ha ésta estafadora, q le dijo al ...
13  @ebenjumea Caterva de bárbaros fueron todos y ...
14  Ayyy Dios mío lo petristas en serio están bien...
15  @Nostrabamu5 Que cumplen el mandato de la cama...
16  @GustavoBolivar Tanta prosperidad y solo utili...
17  @DanielSamperO Dijeron en campaña que iban a v...
18  @PorLasN64213585 @petrogustavo ESO ES VIVIR SA...
19  @MariaFdaCabal está senadora Abla de socialism...
20  Sin tetas NO hay paraíso\nParaíso fiscal, vivi...
21  @XPost1A Totalmente muy de acuerdo con usted m...
22  Se debe sentir mucha impotencia, como la que s...
23  @cabasgustavo @fecode Pero dé qué se quejan lo...
24  @ClaudiaLopez Deje de hablar tanta 💩 y dedíque...
25  El gran cambio robando a las personas de bien ...
26  Los profesores se cansaron de vivir sabroso co...
27  @PizarroMariaJo @wilsonariasc olmedo lopez pre...
28  @ElPensador75 olmedo lopez presidente\neuclide...
29  @NoticiasRCN 😂😂😂luego esos zoquetes no votaron...